# Numpy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5] #indexing start from 0

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
slice_of_array = arr[0:6]
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [13]:
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [14]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr_copy = arr.copy()

In [16]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Create 2D array

In [18]:
arr_2D = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
arr_2D[0][0]

5

In [20]:
arr_2D[0]

array([ 5, 10, 15])

In [22]:
arr_2D[1][2]

30

In [23]:
arr_2D[1,2]

30

In [24]:
arr_2D[2,0]

35

In [38]:
arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
arr_2D[:2,1:]

array([[10, 15],
       [25, 30]])

In [40]:
arr_2D[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [41]:
arr = np.arange(0,11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
bool_arr = arr > 5

In [46]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [47]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [48]:
arr[arr < 3]

array([0, 1, 2])

In [49]:
arr_2D = np.arange(50).reshape(5,10)

In [51]:
arr_2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [52]:
arr_2D[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [65]:
arr_2D[1:7, 7:9]

array([[17, 18],
       [27, 28],
       [37, 38],
       [47, 48]])