# NumPy : Numerical Python
NumPy is the foundaentional package for mathematical computing in Python.
Why Numpy?
supports a multidimensional arrays over which you can easily apply mathematical operations.

In [2]:
import numpy as np

In [3]:
distance = [10,15,17,26]
time = [.30, .47, .55, 1.20]

In [4]:
speed = distance/time # this gives us error unsupported operand type(s) for /: 'list' and 'list'
# so use numpy

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [ ]:
np_distance = np.array(distance)
np_time = np.array(time)
speed = np_distance / np_time

In [5]:
print(speed)

NameError: name 'speed' is not defined

# Create and Print a NumPy array

In [6]:
#import NumPy Library
import numpy as np

In [7]:
#create a first numpy array
first_np_array = np.array([1,2,3,4])

In [8]:
#print the first array
print(first_np_array)

[1 2 3 4]


In [9]:
#arrays with zeros
zeros_np_array = np.zeros([4,2])
zeros_np_array

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
#array with ones
array_with_ones = np.ones([3,3])
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#array with empty
array_with_empty = np.empty([2,3])
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#array with arrange method
array_np_arrange = np.arange(12)
array_np_arrange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
#reshape method to change or create array
array_np_arrange.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [19]:
#linspace for linearly (equal) spaced data element
n_linspace = np.linspace(1,4,4)
n_linspace

array([1., 2., 3., 4.])

In [22]:
#one dimensional array
oneD_array = np.arange(15)
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
#two dimensional array
twoD_array = oneD_array.reshape(3,5)
twoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
#three dimensional array 
threeD_array = np.arange(27).reshape(3,3,3)
threeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [26]:
linspace_array = np.linspace(4,13,7)
linspace_array

array([ 4. ,  5.5,  7. ,  8.5, 10. , 11.5, 13. ])